server:
    port: 8081
spring:
    application:
        name: stock-service
    datasource:
        url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
    jpa:
        show-sql: true
seata:
    enabled: true
    application-id: stock-service
    tx-service-group: my_test_tx_group
    client:
        rm:
            async-commit-buffer-limit: 1000
            report-retry-count: 5
            table-meta-check-enable: false
            report-success-enable: false
            lock:
                retry-interval: 10
                retry-times: 30
                retry-policy-branch-rollback-on-conflict: true
        tm:
            commit-retry-count: 5
            rollback-retry-count: 5
        undo:
            data-validation: true
            log-serialization: jackson
            log-table: undo_log
        log:
            exceptionRate: 100
    service:
        vgroup-mapping:
            my_test_tx_group: default
        grouplist:
            default: ${SEATA_HOST}:${SEATA_PORT}
#        enable-degrade: false
#        disable-global-transaction: false
    transport:
        shutdown:
            wait: 3
        thread-factory:
            boss-thread-prefix: NettyBoss
            worker-thread-prefix: NettyServerNIOWorker
            server-executor-thread-prefix: NettyServerBizHandler
            share-boss-worker: false
            client-selector-thread-prefix: NettyClientSelector
            client-selector-thread-size: 1
            client-worker-thread-prefix: NettyClientWorkerThread
            worker-thread-size: default
            boss-thread-size: 1
        type: TCP
        server: NIO
        heartbeat: true
        serialization: seata
        compressor: none
        enable-client-batch-send-request: true
    config:
        type: file
    registry:
        type: file